/*
 * Wurbelizer tutorial.
 */

package com.example;

/*
 * @> .$filename
 * String    name       the name
 * long      id         the unique ID
 * boolean   enabled    whether enabled or not
 * @<
 */

/**
 * A very simple data transfer object.
 */
public class SampleDTO {

  // @wurblet dto DTO .$filename

  //<editor-fold desc="code 'dto' generated by wurblet DTO">//GEN-BEGIN:dto

  private final String name;  // the name
  private final long id;  // the unique ID
  private final boolean enabled;  // whether enabled or not

  /**
   * Creates a SampleDTO.
   *
   * @param name the name
   * @param id the unique ID
   * @param enabled whether enabled or not
   */
  public SampleDTO(String name, long id, boolean enabled) {
    this.name = name;
    this.id = id;
    this.enabled = enabled;
  }

  /**
   * Gets the name.
   *
   * @return the name
   */
  public String getName() {
    return name;
  }

  /**
   * Gets the unique ID.
   *
   * @return the unique ID
   */
  public long getId() {
    return id;
  }

  /**
   * Gets whether enabled or not.
   *
   * @return whether enabled or not
   */
  public boolean isEnabled() {
    return enabled;
  }

  //</editor-fold>//GEN-END:dto

}
